name: Add Theme
description: add your theme to repo
title: "[Theme]: <name>"
labels: ["theme"]
assignees:
  - flick0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to write this theme request!
  - type: input
    id: repo
    attributes:
      label: git repository which includes your theme
      placeholder: repo url
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: branch to be used on the above git repo (leave empty to use the default branch)
      placeholder: branch name
    validations:
      required: false
  - type: input
    id: desc
    attributes:
      label: description
      placeholder: write a description for your theme
    validations:
      required: false
  - type: input
    id: config
    attributes:
      label: path to the config file of your theme (default ./theme.conf)
      placeholder: theme.conf
    validations:
      required: false
  
    
