name: approve theme

on:
 issues:
  types:
   - labeled

permissions: write-all

jobs:
  approve:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - name: add submodule
        run: |
          echo '${{ fromJson(steps.parse.outputs.payload).Branch }}'
          git submodule add -b '${{ fromJson(steps.parse.outputs.payload).Branch }}' -- '${{ fromJson(steps.parse.outputs.payload).Repo }}' 
      - name: commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            theme request approved, submmodule added
          labels: |
            approved
            theme          
            
  deny:
    if: github.event.label.name == 'denied'
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            theme request denied
          labels: |
            denied
            theme
      
        
    
