name: approve theme

on:
 issues:
  types:
   - labeled

permissions: read-all|write-all

jobs:
  approve:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - name: add submodule
        run: |
          git submodule add "$(tail -n +3 <<< $"${{ github.event.issue.body }}")"
      - name: commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            theme request approved, submmodule added
          labels: |
            approved
            theme
  send_pr:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: pull_repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ..
          ls -a
          repo="$(tail -n +3 <<< $"${{ github.event.issue.body }}")"
          name="$(echo $repo | grep -o '[^/]*$')"
          gh repo fork $repo --clone
          cd "${name/.git/}"
          mkdir .github/workflows/
          cp ../theme-repo/util/updater_submodule.yml .github/workflows/
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - add updater submodule"
          git add -A
          git commit -am "add updater workflow"
          gh pr create -R $repo --base
          
          
          
          

  deny:
    if: github.event.label.name == 'denied'
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            theme request denied
          labels: |
            denied
            theme
      
        
    
